fprintf(1,'Executing %s at %s:\n',mfilename(),datestr(now));
ver,
try,
        %% Generated by nipype.interfaces.spm
        if isempty(which('spm')),
             throw(MException('SPMCheck:NotFound', 'SPM not in matlab path'));
        end
        [name, version] = spm('ver');
        fprintf('SPM version: %s Release: %s\n',name, version);
        fprintf('SPM path: %s\n', which('spm'));
        spm('Defaults','fMRI');

        if strcmp(name, 'SPM8') || strcmp(name(1:5), 'SPM12'),
           spm_jobman('initcfg');
           spm_get_defaults('cmdline', 1);
        end

        jobs{1}.spm.spatial.coreg.estwrite.roptions.prefix = 'r';
jobs{1}.spm.spatial.coreg.estwrite.source = {...
['/neurospin/ciclops/people/Renata/ReconstructedData/31P_Volunteer/2020-08-28/fl200200/1_012_mprage_sag_T1_160sl_iPAT2_20200819/fl200200_20200819_001_012_mprage_sag_T1_160sl_iPAT2.nii'];...
};
jobs{1}.spm.spatial.coreg.estwrite.ref = {...
['/neurospin/ciclops/people/Renata/ReconstructedData/31P_Volunteer/2020-08-28/fl200200/1_002_t1_mpr_tra_iso2_0mm_20200828/fl200200_20200828_001_002_t1_mpr_tra_iso2_0mm.nii'];...
};

        spm_jobman('run', jobs);

        
        if strcmp(name, 'SPM8') || strcmp(name(1:5), 'SPM12'),
            close('all', 'force');
        end;
            
,catch ME,
fprintf(2,'MATLAB code threw an exception:\n');
fprintf(2,'%s\n',ME.message);
if length(ME.stack) ~= 0, fprintf(2,'File:%s\nName:%s\nLine:%d\n',ME.stack.file,ME.stack.name,ME.stack.line);, end;
end;